name: Build and Release

on:
    push:
        branches: [ master ]
        paths:
          - 'src/**'
          - 'manifest.json'
          - 'style.css'
          - 'versions.json'
    pull_request:
        branches: [ master ]
        paths:
          - 'src/**'
          - 'manifest.json'
          - 'style.css'
          - 'versions.json'


jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        strategy:
            matrix:
                node-version: [22.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Build
              run: npm run build
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: v${{ github.run_number }} # 実行番号をタグに使用
                files: |
                  main.js
                  manifest.json
                  style.css
                  versions.json


